Repository shakacode/control-plane-flow, pull requests merged in 2023-07, with the labels that each got.

#58 Add ps:wait command
  docs/commands.md
  lib/command/ps_start.rb
  lib/command/ps_stop.rb
  lib/command/ps_wait.rb
  lib/core/controlplane.rb
  spec/command/maintenance_off_spec.rb
  spec/command/maintenance_on_spec.rb
Labels: enhancement

#15 Update changelog
  CHANGELOG.md
Labels: documentation

#61 Add --use-local-token option to run:detached command
  docs/commands.md
  lib/command/run_detached.rb
Labels: enhancement

#62 Fix run commands when specifying image
  docs/commands.md
  lib/command/run.rb
  lib/command/run_detached.rb
Labels: bug

#63 Fix run:cleanup command for non-interactive workloads
  docs/commands.md
  lib/command/run_cleanup.rb
  spec/cassettes/Command_MaintenanceOff/disables_maintenance_mode.yml
  spec/cassettes/Command_MaintenanceOff/displays_error_if_maintenance_workload_is_not_found.yml
  spec/cassettes/Command_MaintenanceOn/displays_error_if_maintenance_workload_is_not_found.yml
  spec/cassettes/Command_MaintenanceSetPage/displays_error_if_maintenance_workload_is_not_found.yml
  spec/cassettes/Command_MaintenanceSetPage/does_nothing_if_maintenance_workload_does_not_use_shakacode_image.yml
  spec/cassettes/Command_RunCleanup/deletes_stale_run_workloads.yml
  spec/cassettes/Command_RunCleanup/displays_empty_message.yml
  spec/cassettes/Command_RunCleanup/lists_stale_run_workloads.yml
  spec/cassettes/Command_RunCleanup/skips_delete_confirmation.yml
  spec/command/run_cleanup_spec.rb
Labels: bug

#64 Fix run:cleanup command for all apps that start with name
  lib/command/info.rb
  lib/command/run_cleanup.rb
  lib/core/config.rb
  lib/core/controlplane.rb
  lib/core/controlplane_api.rb
  spec/cassettes/Command_RunCleanup/deletes_stale_run_workloads_for_all_apps_that_start_with_name.yml
  spec/cassettes/Command_RunCleanup/lists_stale_run_workloads_for_all_apps_that_start_with_name.yml
  spec/cassettes/Command_RunCleanup/skips_delete_confirmation_for_all_apps_that_start_with_name.yml
  spec/command/run_cleanup_spec.rb
  spec/fixtures/config.yml
Labels: bug

#65 Fix cleanup-old-images command for all apps that start with name
  lib/command/cleanup_old_images.rb
  lib/core/controlplane.rb
Labels: bug

#66 Fix --help option
  CONTRIBUTING.md
  bin/cpl
  cpl
  examples/circleci.yml
  lib/command/test.rb
  lib/cpl.rb
  lib/main.rb
Labels: bug

#67 Update changelog
  CHANGELOG.md
Labels: documentation

#68 fix: run commands fail when not providing image
  lib/command/run.rb
  lib/command/run_detached.rb
Labels: bug

#69 docs: update changelog
  CHANGELOG.md
Labels: documentation

#71 docs: update docs for run commands regarding passing arguments at the end
  CHANGELOG.md
  docs/commands.md
  lib/command/run.rb
  lib/command/run_detached.rb
Labels: documentation
